################################################
#############配置内嵌tomcat############
################################################
server:
  # 服务端口
  port: 8080
  # 项目contextPath，一般在正式发布版本中，我们不配置
  context-path: /
  # 该服务绑定IP地址，启动服务器时如本机不是该IP地址则抛出异常启动失败，只有特殊需求的情况下才配置
  #address: 192.168.16.11
  # session最大超时时间(分钟)，默认为30
  session:
    timeout: 60

################################################
#############添加mysql的数据库配置支持############
################################################
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/utils?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
    
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 10
      max-wait: 10
      min-idle: 1
      max-idle: 1
#模板引擎
  thymeleaf:
      mode: HTML5
#mybatis配置
mybatis:
  type-aliases-package: com.sun.utils.model
  mapper-locations: classpath:mappers/*Mapper.xml  
    